# Generated by Django 4.2.6 on 2023-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField(unique=True)),
                ('error_name', models.CharField(max_length=255)),
            ],
        ),
    ]
