# Generated by Django 4.2.6 on 2023-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/images/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_vendor', models.CharField(max_length=255)),
                ('product_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='errorcode',
            name='error_first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='error_second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='error_third',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
