# Generated by Django 4.2.6 on 2023-10-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixr_api', '0002_product_errorcode_error_first_errorcode_error_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='error_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fixr_api.errorcode'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='error_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
