# Generated by Django 4.2.6 on 2023-10-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixr_api', '0003_product_error_code_alter_errorcode_error_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_link',
        ),
    ]
