# Generated by Django 4.2.6 on 2023-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixr_api', '0005_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
